
create table orders (
    order_id text,
    order_date text,
    order_year text,
    order_month text,
    order_day text,
    order_hour text,
    order_minute text,
    order_second text,
    is_weekend text,
    order_status text,
    return_reason text,
    customer_id text,
    customer_name text,
    gender text,
    age text,
    customer_segment text,
    country text,
    city text,
    customer_loyalty_score text,
    total_orders_by_customer text,
    account_creation_date text,
    product_id text,
    product_name text,
    category text,
    sub_category text,
    brand text,
    product_rating_avg text,
    product_reviews_count text,
    stock_quantity text,
    unit_price_usd text,
    quantity text,
    discount_percent text,
    discount_amount_usd text,
    total_price_usd text,
    cost_usd text,
    profit_usd text,
    tax_usd text,
    currency text,
    payment_method text,
    payment_status text,
    installment_plan text,
    shipping_method text,
    shipping_cost_usd text,
    delivery_days text,
    shipping_country text,
    warehouse_location text,
    delivery_status text,
    rating text,
    review_sentiment text,
    customer_feedback text,
    coupon_used text,
    coupon_code text,
    campaign_source text,
    device_type text,
    traffic_source text,
    session_duration_minutes text,
    pages_visited text,
    abandoned_cart_before text,
    fraud_risk_score text,
    profit_margin_percent text,
    order_priority text,
    support_ticket_created text
);

--\copy orders from '/Users/bolu/supabase/tmp/ecommerce_dataset_small.csv' WITH (FORMAT csv, HEADER true);
\copy orders from '/Users/bolu/supabase/tmp/ecommerce_dataset_large.csv' WITH (FORMAT csv, HEADER true);
